### ISSUE TITLE
how to generate sourceMaps for production mode?

### ISSUE THREAD

**Issue by zaggino** [bradleyboy/yarsk#10]

**Comment by bradleyboy** [comment]
Open `conf/webpack.production.js` and change it to:

``` js
module.exports = require('./make-webpack-config')({
  production: true,
  devtool: 'source-map'
});
```

Then when you build, sourcemaps will be generated for both CSS and JS.

**Comment by zaggino** [comment]
thanks a lot, commented out line in code could be also useful for others... i've just started exploring devpack coming from browserify :) i've gone through a few starters but yours is the first one not overcomplicating things (except the most basic one)

**Comment by tshddx** [comment]
Is this supposed to generate maps with the actual ES6 code, before transpilation? It doesn't seem to have any effect for me. With or without the source-map options, I can still see all my index.jsx files in the Chrome Sources tab, but they are post-transpilation.

**Comment by bradleyboy** [comment]
@baddox Is this in production or development? In development, `eval` is used, which will show the sourcemap post-transpilation. You can change that by editing the devtool setting in `conf/webpack.config.js`:

``` js
module.exports = require('./make-webpack-config')({
  devtool: 'eval-source-map',
});
```

Keep in mind that the compilation and rebuilds will be slightly slower with that setting. More on the devtool options can be found in the [webpack docs](http://webpack.github.io/docs/configuration.html#devtool).

**Comment by tshddx** [comment]
Indeed, that was my issue in development.
