### ISSUE TITLE
Babel polyfill required for some features/browsers

### ISSUE THREAD

**Issue by tshddx** [bradleyboy/yarsk#13]
Forgive me if this is common knowledge, but it might be nice to throw something in the README about needing to `npm install babel --save` and put `require("babel/register");` into `Application/index.jsx`. This includes the [Babel polyfill](https://babeljs.io/docs/usage/polyfill/) in the build, which I believe is required in certain browsers for things like `Symbol.iterator`. My app was failing to load on iOS and OS X Safari without the polyfill.

**Comment by bradleyboy** [comment]
@baddox Good point. I've added babel to the dependencies and also added a commented out line to `app/index.jsx` so people know it is there.

One thing to note is that you should use `require('babel/polyfill');` not `require('babel/register');` as the latter runs all future requires through babel, something that webpack is already doing.

**Comment by tshddx** [comment]
Good point on polyfill vs. register. Thanks.
