### ISSUE TITLE
40KB bundle?

### ISSUE THREAD

**Issue by julesmoretti** [bradleyboy/yarsk#33]
So I followed your step by step which was pretty flawless for now. But this is the output I get:

```
                               Asset       Size  Chunks             Chunk Names
f81123791caadd01a948c1bc8d3082ef.jpg     766 kB          [emitted]  
         app.5424fa5a93311efc1d88.js     154 kB       0  [emitted]  main
        app.5424fa5a93311efc1d88.css    1.98 kB       0  [emitted]  main
                          index.html  398 bytes          [emitted]  

```

Therefore it seems that your bundle size is really more like 154kB rather than 40...

Could you please check on your end. Because if you get 40kB I want to know how :)

**Comment by bradleyboy** [comment]
@julesmoretti It's 40KB once gzipped. Try:

`gzip app.5424fa5a93311efc1d88.js` and inspect the size of the gzipped version. Assuming your server gzips static assets, you should be set to go by shipping the 154KB version.

**Comment by julesmoretti** [comment]
Yup! very cool! thank you!
