### ISSUE TITLE
Getting err about lodash

### ISSUE THREAD

**Issue by winkler1** [bradleyboy/yarsk#4]
Trying it out...get this after npm install. Installing lodash does not fix it-

```
$ npm run serve

> bradleyboy-react-starter@1.0.0 serve /Users/Jeff/repos/ghtemp
> webpack-dev-server --config conf/webpack.config.js --hot --progress --colors --inline --content-base ./build

http://localhost:8080/
webpack result is served from /
content is served from /Users/Jeff/repos/ghtemp/build
-25% 1/4 build modules
/Users/Jeff/repos/ghtemp/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:204
                    throw e;
                          ^
Error: Cannot find module 'lodash/lang/isFunction'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Jeff/repos/ghtemp/node_modules/babel-core/lib/babel/api/node.js:13:34)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by bradleyboy** [comment]
@winkler1 That's odd. I just did a fresh clone and didn't get that. Maybe something went wrong during npm install? Can you try deleting node_modules and trying npm install again?

**Comment by winkler1** [comment]
Did some testing--
New machine: Works just fine. `webpack-dev-server -v
-bash: webpack-dev-server: command not found`

Original/bad machine: rm'd node_modules, still fails. Re-cloned, still fails. webpack-dev-server is 1.7.3

The difference could be the fact that the package.json is using the global webpack/dev-server, not within node_modules?

**Comment by bradleyboy** [comment]
Good point. Just pushed a fix that uses the full path to webpack and the dev-server, see if that fixes it.

**Comment by winkler1** [comment]
Unfortunately not on the bad machine. Will try to run some experiments this weekend. I'm thinking to save off global NPM state, see if that makes a difference.
Really like this starter kit btw... I'll add in react-router and probably flummox on real projects, but you're wise to minimize the surface area :)

**Comment by winkler1** [comment]
`npm cache clean` did the trick, closing.
