### ISSUE TITLE
Add expressjs support

### ISSUE THREAD

**Issue by libtool** [bradleyboy/yarsk#8]
Please add the support expressjs

**Comment by bradleyboy** [comment]
Can you expand on this? What would be the benefit of adding express to this starter kit?

**Comment by libtool** [comment]
Support  full stack development and isomorphic appp. I do not insist. In any case, thank you for such a great starter kit!

**Comment by bradleyboy** [comment]
@libtool Understood. This is low on my priority list, but I'd be glad to look at a PR if anyone wants to take a shot at this. I did recently use express with an app based on this kit and made a change in https://github.com/bradleyboy/yarsk/commit/4a4c86d629130fb56552cce05cdd76bfaef9fbca that should help integration with other servers.

**Comment by libtool** [comment]
Thank you!
